name       : mongo-tools
version    : 3.6.3
release    : 7
source     :
    - https://github.com/mongodb/mongo-tools/archive/r3.6.3.tar.gz : d97461a21227a3563e3e362dfda330becff48a901ecb3309241f607c7c8900af
license    : Apache-2.0
component  : programming.tools
summary    : MongoDB tools provide import, export, and diagnostic capabilities
description: |
    The MongoDB tools include: bsondump, mongoimport, mongoexport, mongodump, mongorestore, mongostat, mongofiles, mongooplog, mongotop.
builddeps  :
    - pkgconfig(libsasl2)
    - golang
    - libpcap-devel
rundeps    :
    - mongodb
build      : |
    . ./set_gopath.sh
    mkdir bin
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop mongoreplay; do
        go build -o "bin/$i" -tags "ssl sasl" "$i/main/$i.go"
    done
install    : |
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop mongoreplay; do
      install -Dm00755 bin/$i $installdir/usr/bin/$i
    done
check      : |
    export GOPATH=$PWD/.gopath:$PWD/vendor
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump; do
        (cd $i && go test)
    done
