name       : mongo-tools
version    : 3.6.2
release    : 6
source     :
    - https://github.com/mongodb/mongo-tools/archive/r3.6.2.tar.gz : 4bab8f6ce39d2b9d5c84a2b358817442d21969304ae15b2a252e1a9f0d16bdf5
license    : Apache-2.0
component  : programming.tools
summary    : MongoDB tools provide import, export, and diagnostic capabilities.
description: |
    The MongoDB tools include: bsondump, mongoimport, mongoexport, mongodump, mongorestore, mongostat, mongofiles, mongooplog, mongotop.
builddeps  :
    - pkgconfig(libsasl2)
    - golang
    - libpcap-devel
rundeps    :
    - mongodb
build      : |
    . ./set_gopath.sh
    mkdir bin
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop mongoreplay; do
        go build -o "bin/$i" -tags "ssl sasl" "$i/main/$i.go"
    done
install    : |
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop mongoreplay; do
      install -Dm00755 bin/$i $installdir/usr/bin/$i
    done
