name       : mongo-tools
version    : 3.5.10
release    : 2
source     :
    - https://github.com/mongodb/mongo-tools/archive/r3.5.10.tar.gz : 2a2063060a78fa5f58e0c846421404d74d1523f283b8bc93aa3d1f3d7484d4aa
license    : Apache-2.0
component  : programming.tools
summary    : MongoDB tools provide import, export, and diagnostic capabilities.
description: |
    The MongoDB tools include: bsondump, mongoimport, mongoexport, mongodump, mongorestore, mongostat, mongofiles, mongooplog, mongotop.
builddeps  :
    - pkgconfig(libsasl2)
    - golang
    - libpcap-devel
rundeps    :
    - mongodb
build      : |
    . ./set_gopath.sh
    mkdir bin
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop mongooplog mongoreplay; do
        go build -o "bin/$i" -tags "ssl sasl" "$i/main/$i.go"
    done
install    : |
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop mongooplog mongoreplay; do
      install -Dm00755 bin/$i $installdir/usr/bin/$i
    done
