name       : mongo-tools
version    : 4.0.1
release    : 8
source     :
    - https://github.com/mongodb/mongo-tools/archive/r4.0.1.tar.gz : f3836edb7907603a2d9e5020fe60acabb6a383ee579465eeef885460f6aab30f
license    : Apache-2.0
component  : programming.tools
summary    : MongoDB tools provide import, export, and diagnostic capabilities
description: |
    The MongoDB tools include: bsondump, mongoimport, mongoexport, mongodump, mongorestore, mongostat, mongofiles, mongooplog, mongotop.
builddeps  :
    - pkgconfig(libsasl2)
    - golang
    - libpcap-devel
rundeps    :
    - mongodb
build      : |
    . ./set_gopath.sh
    mkdir bin
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop mongoreplay; do
        go build -o "bin/$i" -tags "ssl sasl" "$i/main/$i.go"
    done
install    : |
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop mongoreplay; do
      install -Dm00755 bin/$i $installdir/usr/bin/$i
    done
check      : |
    export GOPATH=$PWD/.gopath:$PWD/vendor
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump; do
        (cd $i && go test)
    done
