name       : mongo-tools
version    : 4.0.6
release    : 10
source     :
    - git|https://github.com/mongodb/mongo-tools.git : r4.0.6
license    : Apache-2.0
component  : programming.tools
summary    : MongoDB tools provide import, export, and diagnostic capabilities
description: |
    The MongoDB tools include: bsondump, mongoimport, mongoexport, mongodump, mongorestore, mongostat, mongofiles, mongooplog, mongotop.
builddeps  :
    - pkgconfig(libsasl2)
    - golang
    - libpcap-devel
rundeps    :
    - mongodb
build      : |
    mkdir src bin
    mv vendor/* src/
    mkdir -p src/github.com/mongodb
    ln -sv `pwd` src/github.com/mongodb/mongo-tools
    export GOPATH=`pwd`
    VersionStr="$(git describe)"
    Gitspec="$(git rev-parse HEAD)"
    importpath="github.com/mongodb/mongo-tools/common/options"

    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop mongoreplay; do
        go build -o "bin/$i" -ldflags "-X ${importpath}.VersionStr=${VersionStr} -X ${importpath}.Gitspec=${Gitspec}" -tags "ssl sasl" "$i/main/$i.go"
    done
install    : |
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongorestore mongodump mongotop mongoreplay; do
      install -Dm00755 bin/$i $installdir/usr/bin/$i
    done
check      : |
    export GOPATH=`pwd`
    for i in bsondump mongostat mongofiles mongoexport mongoimport mongodump; do
        (cd $i && go test)
    done
